apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: releases/dev1/helm
    repoURL: https://github.com/sachin433/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - Replace=true
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
